# THIS IS NOT TO BE USED FOR PERSONAL DEPLOYMENTS!
# Internal Docker Compose Image used for internal testing deployments

services:
  hoppscotch-db:
    image: postgres:15
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: hoppscotch

  hoppscotch-aio:
    image: hoppscotch/hoppscotch
    environment:
      - DATABASE_URL=postgresql://postgres:testpass@hoppscotch-db:5432/hoppscotch
      - ENABLE_SUBPATH_BASED_ACCESS=false
    env_file:
      - ./.env
    ports:
      - 8080:80
    depends_on:
      - hoppscotch-db
    command: ["sh", "-c", "pnpm exec prisma migrate deploy && node /usr/src/app/aio_run.mjs"]
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80'
      interval: 2s
      timeout: 10s
      retries: 30
